apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: srek3s-sentinel
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: srek3s-sentinel
    {{- include "srek3s.partOf" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: srek3s-sentinel
  policyTypes:
    - Egress
    - Ingress
  ingress: []
  egress:
    - to:
        {{- range .Values.networkPolicy.apiServerCidrs }}
        - ipBlock:
            cidr: {{ . }}
        {{- end }}
      ports:
        - protocol: TCP
          port: 443
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: srek3s-agent
      ports:
        - protocol: TCP
          port: 8000
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
