apiVersion: v1
kind: ServiceAccount
metadata:
  name: srek3s-sentinel
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: srek3s-sentinel
    {{- include "srek3s.partOf" . | nindent 4 }}
automountServiceAccountToken: true
